[package]
name = "qiskit-providers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "qiskit_providers"

[dependencies]
qiskit-circuit.workspace = true
rustworkx-core.workspace = true
num-complex.workspace = true
thiserror.workspace = true
numpy = { workspace = true, optional = true }

[dependencies.approx]
workspace = true
features = ["num-complex"]

[dependencies.hashbrown]
workspace = true
features = ["rayon", "serde"]

[dependencies.ndarray]
workspace = true
features = ["rayon", "approx"]

[dependencies.pyo3]
workspace = true
optional = true
features = ["hashbrown", "num-complex"]

[lints]
workspace = true

[features]
python = ["dep:pyo3", "dep:numpy"]